include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Style
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true

    # Safety
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    unnecessary_null_checks: true
    use_build_context_synchronously: true
    avoid_slow_async_io: true

    # Code quality
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    avoid_returning_null_for_future: true
    unawaited_futures: true
    unnecessary_await_in_return: true
