import 'package:flutter/material.dart';

import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_spacing.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final bodyStyle = Theme.of(context).textTheme.bodyMedium?.copyWith(
          height: 1.6,
          color: isDark ? AppColors.darkTextSecondary : AppColors.textSecondary,
        );
    final headingStyle = Theme.of(context).textTheme.titleSmall?.copyWith(
          fontWeight: FontWeight.w700,
        );

    return Scaffold(
      appBar: AppBar(title: const Text('Terms of Service')),
      body: ListView(
        padding: AppSpacing.screenPadding,
        children: [
          Text(
            'Terms of Service',
            style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 4),
          Text('Last updated: February 2026', style: bodyStyle?.copyWith(fontSize: 12)),
          const SizedBox(height: 20),

          _Section(heading: '1. Acceptance of Terms', headingStyle: headingStyle, body: '''
By accessing or using MedQ ("Service"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, do not use the Service.''', bodyStyle: bodyStyle),

          _Section(heading: '2. Description of Service', headingStyle: headingStyle, body: '''
MedQ is an AI-powered medical study platform that helps medical students organize study materials, generate practice questions, create personalized study plans, and track progress. The Service uses artificial intelligence to process uploaded content and generate educational materials.''', bodyStyle: bodyStyle),

          _Section(heading: '3. Medical Disclaimer', headingStyle: headingStyle, body: '''
MedQ is strictly an educational study tool. It does NOT provide medical advice, diagnosis, or treatment recommendations. Content generated by MedQ should not be used for clinical decision-making. Always consult qualified healthcare professionals for medical advice.''', bodyStyle: bodyStyle),

          _Section(heading: '4. User Accounts', headingStyle: headingStyle, body: '''
You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. You must provide accurate information during registration and keep it up to date.''', bodyStyle: bodyStyle),

          _Section(heading: '5. User Content', headingStyle: headingStyle, body: '''
You retain ownership of content you upload to MedQ. By uploading content, you grant MedQ a limited licence to process, analyse, and generate educational materials from your content solely for your use within the Service.''', bodyStyle: bodyStyle),

          _Section(heading: '6. Acceptable Use', headingStyle: headingStyle, body: '''
You agree not to:
• Upload copyrighted material you don't have rights to
• Use the Service for any unlawful purpose
• Attempt to reverse-engineer the Service
• Share your account credentials with others
• Use automated tools to access the Service''', bodyStyle: bodyStyle),

          _Section(heading: '7. Limitation of Liability', headingStyle: headingStyle, body: '''
MedQ is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to errors in generated content, service interruptions, or data loss.''', bodyStyle: bodyStyle),

          _Section(heading: '8. Changes to Terms', headingStyle: headingStyle, body: '''
We reserve the right to modify these Terms at any time. We will notify users of significant changes. Continued use of the Service after changes constitutes acceptance of the updated Terms.''', bodyStyle: bodyStyle),

          _Section(heading: '9. Contact', headingStyle: headingStyle, body: '''
For questions about these Terms, contact us at support@medq.app.''', bodyStyle: bodyStyle),

          const SizedBox(height: 32),
        ],
      ),
    );
  }
}

class _Section extends StatelessWidget {
  final String heading;
  final TextStyle? headingStyle;
  final String body;
  final TextStyle? bodyStyle;

  const _Section({
    required this.heading,
    this.headingStyle,
    required this.body,
    this.bodyStyle,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(heading, style: headingStyle),
          const SizedBox(height: 6),
          Text(body.trim(), style: bodyStyle),
        ],
      ),
    );
  }
}
