import { Timestamp } from "firebase/firestore";

export interface WeakTopic {
  tag: string;
  weaknessScore: number;
  accuracy: number;
}

export interface StatsModel {
  courseId: string;
  totalStudyMinutes: number;
  totalQuestionsAnswered: number;
  overallAccuracy: number; // 0–1 range
  weeklyStudyMinutes?: number;
  completionPercent: number; // 0–1 range
  weakestTopics: WeakTopic[];
  /** Plain-English action directives generated by computeWeakness */
  diagnosticDirectives?: string[];
  streakDays?: number;
  lastStudiedAt?: Timestamp;
  updatedAt?: Timestamp;
}
