import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - MedQ",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <Link
        href="/"
        className="mb-8 inline-flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground"
      >
        <ArrowLeft className="h-3.5 w-3.5" />
        Back to home
      </Link>

      <h1 className="text-3xl font-semibold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: February 2026
      </p>

      <div className="prose-muted mt-8 space-y-6 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="text-lg font-semibold text-foreground">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using MedQ (&quot;the Service&quot;), you agree to be bound
            by these Terms of Service. If you do not agree, do not use the
            Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            2. Description of Service
          </h2>
          <p>
            MedQ is an AI-powered medical study platform that helps students
            upload materials, generate study plans, take quizzes, and track
            learning progress. The Service uses artificial intelligence to
            generate educational content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            3. Medical Disclaimer
          </h2>
          <p>
            MedQ is an educational study tool only. Content generated by the
            Service is not medical advice and should not be used for clinical
            decision-making or patient care. AI-generated questions and
            explanations may contain errors. Always verify information against
            authoritative medical sources and consult qualified healthcare
            professionals.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            4. User Accounts
          </h2>
          <p>
            You are responsible for maintaining the confidentiality of your
            account credentials and for all activities under your account.
            You must provide accurate information when creating an account.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            5. User Content
          </h2>
          <p>
            You retain ownership of materials you upload. By uploading content,
            you grant MedQ a limited license to process and analyze it solely
            for providing the Service to you. We do not share your uploaded
            materials with other users.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            6. Acceptable Use
          </h2>
          <p>You agree not to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Upload copyrighted materials you do not have rights to use</li>
            <li>Attempt to reverse-engineer or abuse the AI systems</li>
            <li>Use the Service for any unlawful purpose</li>
            <li>Share your account credentials with others</li>
            <li>
              Attempt to circumvent rate limits or other technical restrictions
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            7. Limitation of Liability
          </h2>
          <p>
            The Service is provided &quot;as is&quot; without warranties of any kind.
            MedQ is not liable for any damages arising from your use of the
            Service, including but not limited to inaccuracies in AI-generated
            content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">
            8. Changes to Terms
          </h2>
          <p>
            We may update these terms at any time. Continued use of the
            Service after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">9. Contact</h2>
          <p>
            For questions about these terms, contact us at{" "}
            <a
              href="mailto:support@medq.app"
              className="text-primary hover:underline"
            >
              support@medq.app
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
